# Generated by Django 2.2.5 on 2019-10-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='DOB',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
