# Generated by Django 2.2.5 on 2019-10-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0003_nominance_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominance',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
